server:
  port: 8083
spring:
  application:
    name: vivo_backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://121.43.109.60:9712/vivo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  aliyun:
    oss:
      file:
        endpoint: oss-cn-nanjing.aliyuncs.com
        keyid: LTAI5tPUru8Te21FKZaNPr1e
        keysecret: QLdTCUQzz0n07VzDYpPtRHj8FrobtU
        bucketname: ossforvivobackend
        filedir: val/

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.vivo_backend.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰自动映射
    cache-enabled: false # 禁用缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##阿里云 OSS配置
#  aliyun.oss.file.endpoint=你的服务器地址，不同的服务器，地址不同
#    aliyun.oss.file.keyid=你的keyid
#    aliyun.oss.file.keysecret=key的秘钥
#    #bucket可以在控制台创建，也可以使用java代码创建
#    aliyun.oss.file.bucketname=你创建的bucket
#    aliyun.oss.file.filehost=上传的目录
